#!/usr/bin/env bash
perc=$(cat /sys/class/power_supply/BAT0/capacity) 
charging_status=$(cat /sys/class/power_supply/BAT0/status)
icon="󰂑"
case $charging_status in
	Discharging)
		case $perc in 
			[0-9])
                notify-send  -t 10000 -w "Battery is low, please plug me bro"
				icon="󱃍"
				;;
			1[0-9])
				icon="󰁺"
				;;
			2[0-9])
				icon="󰁻"
				;;

			3[0-9])
				icon="󰁼"
				;;


			4[0-9])
				icon="󰁽"
				;;

			5[0-9])
				icon="󰁾"
				;;
			6[0-9])
				icon="󰁿"
				;;
			7[0-9])
				icon="󰂀"
				;;
			8[0-9])
				icon="󰂁"
				;;

			9[0-9])
				icon="󰂂"
				;;

			100)
				icon="󰁹"
				;;
			esac
			;;

	Charging)
		case $perc in 
			[0-9])
				icon="󰢟"
                
				;;
			1[0-9])
				icon="󰢜"
				;;
			2[0-9])
				icon="󰂆"
				;;

			3[0-9])
				icon="󰂇"
				;;

			4[0-9])
				icon="󰂈"
				;;

			5[0-9])
				icon="󰢝"
				;;
			6[0-9])
				icon="󰂉"
				;;
			7[0-9])
				icon="󰢞"
				;;
			8[0-9])
				icon="󰂊"
				;;

			9[0-9])
				icon="󰂋"
				;;

			100)
				icon="󰂄"
				;;
			esac
			;;
        Full)
            icon="󰁹"
            ;;
	esac
echo "$icon$perc%"
